# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Make Everyday Count
email: nickxiao@me.com
description: >
  人如果没有梦想, 那和咸鱼有什么分别
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nicoster.github.io" # the base hostname & protocol for your site
paginate:	10 # The number of posts to show per page on your homepage

name: 'Nick Xiao'
bio: >
  2007 加入 Cisco, 一直致力于协作平台的客户端研发, 作为 Technical Leader 负责平台架构设计. 熟悉 XMPP 协议. 对 C/C++, x86/arm 汇编, windbg, Windows Troubleshooting 等有深入研究. 2014 转向协作平台后端的研发. 主导系统整体架构设计. 对系统 Troubleshooting, Erlang, Ejabberd, Nginx, Lua, Redis 以及 分布式系统, 高并发, 性能调优都有深入的研究和丰富的实战经验. 善于使用脚本编写各种工具避免重复劳动, 提高自己和团队日常工作效率.
author_image: "/assets/images/author.jpg"
twitter_username: nicoster
github_username:  nicoster

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
